#!/bin/sh
#
# 2013 - 2014 Thomas Oettli    (otho at sfs.biz)
# 2013 - 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of sfs-cdist-types.
#
# sfs-cdist-types is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sfs-cdist-types is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sfs-cdist-types. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/version" ]; then
    version="$(cat "$__object/parameter/version")"
fi

if [ -f "$__type/files/ntp.conf-${version}" ]; then
    # install ntp if needed
    __package ntp --state present

    # install ntp config file
    require="__package/ntp" __file /etc/ntp.conf --state present --source "$__type/files/ntp.conf-${version}"

    # add ntp to default runlevel
    require="__package/ntp" __start_on_boot ntp

    # start ntp if not yet running
    require="__package/ntp" __process ntpd --state present --start "/etc/init.d/ntp start >/dev/null" --name "/usr/sbin/ntpd.*"
else
    echo "Warning: NTP configuration for ${version} is not implemented yet" >&2
    exit 1
fi
