#!/bin/sh
#
# 2013 - 2014 Thomas Oettli    (otho at sfs.biz)
# 2013 - 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of sfs-cdist-types.
#
# sfs-cdist-types is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sfs-cdist-types is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sfs-cdist-types. If not, see <http://www.gnu.org/licenses/>.
#


if command -v smsap >/dev/null; then
    echo $(smsap version | cut -d ":" -f 2 | cut -c 2-)
fi
