#!/bin/sh
#
# 2013 - 2014 Thomas Oettli    (otho at sfs.biz)
# 2013 - 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of sfs-cdist-types.
#
# sfs-cdist-types is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sfs-cdist-types is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sfs-cdist-types. If not, see <http://www.gnu.org/licenses/>.
#
# install cciss_vol_status

if [ -f "$__object/parameter/version" ]; then
    version="$(cat "$__object/parameter/version")"
fi

installed_version="$(cat "$__object/explorer/installed_version")"

[ "${installed_version}" = "${version}" ] && exit 0

if [ -f "$__type/files/${version}/pdftk-${version}-src.zip" ]; then
    # install gcc, we need it
    __package gcc-java --state present
    __package gcc-c++ --state present
    __package fastjar --state present

    # copy source package to target host
    __file /tmp/pdftk-${version}-src.zip --state present --source "$__type/files/${version}/pdftk-${version}-src.zip"
    __file /tmp/Makefile.SLES11 --state present --source "$__type/files/${version}/Makefile.SLES11"
    __file /usr/local/bin/runpdftk.sh --state present --source "$__type/files/${version}/runpdftk.sh"
    __file /usr/local/bin/runpdftk_a4.sh --state present --source "$__type/files/${version}/runpdftk_a4.sh"
    __file /usr/local/bin/gs-907 --state present --source "$__type/files/${version}/gs-907"
else
    echo "Warning: pdftk-${version} is not implemented yet" >&2
    exit 1
fi
