#!/bin/sh
#
# 2013 - 2014 Thomas Oettli    (otho at sfs.biz)
# 2013 - 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of sfs-cdist-types.
#
# sfs-cdist-types is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sfs-cdist-types is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sfs-cdist-types. If not, see <http://www.gnu.org/licenses/>.
#


if [ -f "$__object/parameter/version" ]; then
    version="$(cat "$__object/parameter/version")"
fi

installed_version="$(cat "$__object/explorer/installed_version")"

[ "${installed_version}" = "${version}" ] && exit 0
# start multipath
echo "/etc/init.d/multipathd start &> /dev/null"
# install package
echo "cd /tmp"
echo "rpm -U netapp.snapdrive.linux_${version}.rpm &> /dev/null || exit 1"
# copy init script and config file
echo "cp -a snapdrive.conf /opt/NetApp/snapdrive/snapdrive.conf"
echo "cp -a snapdrived.initd /etc/init.d/snapdrived"
echo "cp -a .pwfile /opt/NetApp/snapdrive/"
echo "cp -a .sdupw /opt/NetApp/snapdrive/"
echo "insserv -rf snapdrived"
echo "insserv -d snapdrived"
echo "snapdrived restart &> /dev/null"
# cleanup
echo "cd /tmp"
echo "rm -f netapp.snapdrive.linux_${version}.rpm"
echo "rm -f snapdrive.conf"
echo "rm -f snapdrived.initd"
echo "rm -f .pwfile"
echo "rm -f .sdupw"
