#!/bin/sh
#
# 2013 - 2014 Thomas Oettli    (otho at sfs.biz)
# 2013 - 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of sfs-cdist-types.
#
# sfs-cdist-types is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sfs-cdist-types is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sfs-cdist-types. If not, see <http://www.gnu.org/licenses/>.
#
# install snapmanager

if [ -f "$__object/parameter/version" ]; then
    version="$(cat "$__object/parameter/version")"
fi

installed_version="$(cat "$__object/explorer/installed_version")"

[ "${installed_version}" = "${version}" ] && exit 0

if [ -f "$__type/files/${version}/netapp.smsap.linux-x64-${version}.bin" ]; then
    # copy source package to target host
    __file /tmp/netapp.smsap.linux-x64-${version}.bin --state present --source "$__type/files/${version}/netapp.smsap.linux-x64-${version}.bin" --mode 0700
    __file /tmp/installer.properties --state present --source "$__type/files/${version}/installer.properties" --mode 0644
    # copy config to target host
    __file /tmp/smsap.config --state present --source "$__type/files/${version}/smsap.config" --mode 0644
    __file /tmp/snapmanager.pamd --state present --source "$__type/files/${version}/snapmanager.pamd" --mode 0644
    __file /tmp/smsap_server.initd --state present --source "$__type/files/${version}/smsap_server.initd" --mode 0755
    # create required user and group
    __group dba --gid 201
    require="__group/dba" __user oracle --uid 400 --gid dba --comment "Database Administrator" --system
else
    echo "Warning: snapmanager-${version} is not implemented yet" >&2
    exit 1
fi
